blank_issues_enabled: false
contact_links:
  - name: "Support Forum"
    url: "https://your-support-forum.example.com"
    about: "If you have a question or need help, please visit our support forum."
